import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class ServicesTarjetasService {

  private listaInfo: any [] = [
    {
       img:"../../../assets/img/info/terrans.jpg",
       titulo: "La Confederacion Terrans",
       info: ` 
       La caída de la civilización occidental
       Aunque la tecnología y la cultura mundial habían progresado mucho durante todo el siglo XX, esos avances resultaron incomparables frente al posterior desarrollo, casi temerario. Al final del siglo XXI, el ser humano había sido testigo de atrevidos cambios. Tecnologías radicalmente nuevas aparecían a increíbles velocidades, ofreciendo el acceso a ordenadores avanzados y bases de datos de información hasta los países más necesitados de la Tierra. El comunismo cayó en los países del este, en poco tiempo hubo cantidad de armas nucleares disponibles y la estructura de poder internacional, definida originalmente por la adquisición de capital y la superioridad militar, quedó destruida cuando los países del Tercer Mundo se levantaron para desafiar al poder militar y económico de las superpotencias mundiales.
       Como las manipuladas ciencias de la cibernética, de la clonación y del encolado genético habían ido apareciendo paulatinamente en el foro público, grupos de militares humanistas y religiosos de línea dura se enfrentaron a las corporaciones de intereses privados que hacían beneficios mediante la experimentación genética. Estos dramáticos cambios en la reserva genética humana desataron una gran alarma entre las principales facciones humanistas.      
       La tecnología siguió desarrollándose, y los índices de población aumentaron. Al final del siglo XXI había 8 mil millones de personas en la Tierra, y en solo 300 años, la población había aumentado en 26 mil millones. La contaminación, la falta de recursos naturales y combustibles asequibles aún empeoraban más las cosas mientras los líderes mundiales buscaban la forma de detener el crecimiento de la población en sus respectivos países. El sentimiento popular era que el mundo se dirigía a una inevitable catástrofe porque la superpoblación y la alteración genética lo invadían todo.
       Mientras tanto, a medida que crecían las tensiones internacionales en cuanto al uso y capitalización de las mutaciones genéticas y cibernéticas, muchos sistemas económicos internacionales se replegaron sobre sí mismos y se cerraron. Se produjeron horribles actos de terrorismo entre el sector corporativo y las facciones humanistas, obligando a acciones de fuerza de la policía por todo el mundo. La irresponsable cobertura informativa de los medios de comunicación de estas atroces acciones policiales extendieron el caos civil ya existente en muchos de los países más grandes. Finalmente la precaria balanza del poder mundial estalló en un pandemónium internacional`
    },
    {
       img:"../../../assets/img/info/zergs.jpg",
       titulo: "El Enjambre Zergs",
       info: `El nacimiento de los Zerg
       Tras viajar miles de años luz por el interior del ardiente núcleo de la galaxia, los Xel'Naga acabaron asentándose en el mundo de Zerus. Los Xel'Naga decidieron continuar con su Gran Experimento evolutivo, solo que esta vez ignoraron sus dogmas en cuanto a la forma física y se centraron principalmente en la búsqueda de una "pureza de esencia". Estacionados en sus enormes naves muy por encima de Zerus, los Xel'Naga empezaron una vez más a desafiar las artimañas del destino.
       Los Xel'Naga consiguieron más éxito con su segunda empresa de lo que ellos podrían haberse imaginado, trabajando esta vez para acelerar la evolución de la forma de vida más insignificante de Zerus, una raza de insectoides en miniatura conocida como los Zerg. Gracias a las manipulaciones protogénicas de los Xel'Naga, los Zerg sobrevivieron a las continuas tormentas de fuego de su mundo y evolucionaron. A pesar de ser extremadamente pequeños, de su aspecto de orugas y de su incapacidad para manipular físicamente su entorno, los Zerg se adaptaron y sobrevivieron. Los Zerg desarrollaron la habilidad de enterrarse en la carne de las especies indígenas menos vulnerables de Zerus alimentándose de los nutrientes contenidos dentro de los fluidos vitales uniéndose como parásitos. Cuando fueron capaces de controlar los procesos metabólicos y anatómicos de sus anfitriones, los Zerg utilizaron sus nuevos cuerpos para manipular el entorno.
       A medida que los Zerg incorporaban a más y más criaturas anfitrionas en sus rebaños, empezaron a asimilar sus diversos procesos y cepas genéticas. La química de los Zerg empezó a mutar y a adaptarse al volumen del nuevo material genético que estaba siendo procesado. Sin embargo, a pesar de la gran variedad de criaturas anfitrionas, existía siempre un impulso innato a consumir solamente las especies más avanzadas evolutivamente con las que se encontraban. Los Zerg eran innatamente selectivos en cuanto a que especies consumir asegurándose en cada etapa del desarrollo que ellos estaban siempre en la parte superior de la proverbial cadena alimenticia. Cualquier raza encontrada por los Zerg que no fuera considerada como válida de asimilación fue erradicada para purificar aún más la raza.
       Pero pronto los Xel'Naga descubrirían algo muy alarmante. Las razas originales asimiladas por los Zerg apenas eran reconocibles después de solo unas cuantos generaciones de su ingestión. De alguna manera, los Zerg habían desarrollado la habilidad de sobrecargar y dirigir los latentes procesos evolutivos existentes dentro de sus criaturas anfitrionas. Las criaturas anfitrionas sufrieron los efectos de grandes mutaciones físicas que hicieron que a todas las especies Zerg les crecieran púas perforadoras de blindaje, miembros afilados como cuchillas y caparazones ultra densos. Tras un sorprendente corto espacio de tiempo, las especies evolucionaron hasta parecer una sola raza terriblemente voraz.`
    },
    {
       img:"../../../assets/img/info/protoss.jpg",
       titulo: "Los Ejecutores Protoss",
       info: `Aunque solamente quedan pequeños fragmentos de documentación, los antiguos textos Protoss hablan de una raza muy avanzada que gobernó en miles de mundos de la galaxia hace decenas de millones de años. Se rumoreaba que esta enigmática raza, frecuentemente llamada los Xel'Naga o "viajeros de la lejanía" habían sembrado y cultivado miles de especies diferentes en los fríos y estériles mundos dentro de su dominio. Las tradiciones Protoss mantienen que los Xel'Naga eran una raza pacífica y benevolente totalmente dedicada al estudio y la propagación de la evolución sensible dentro del universo. No se sabe nada del origen de los Xel'Naga salvo que no eran nativos de la galaxia que dominaban. Obsesionados con conseguir la forma de vida perfecta, los Xel'Naga se esforzaron en crear una criatura que estuviera definida por una marcada "pureza de forma".
       Durante miles de años dirigieron los delicados procesos evolutivos de sus especies en ciernes. A pesar de que sus prolongados experimentos produjeron muchas desviaciones y mutaciones intrigantes, las razas que los Xel´Naga cultivaban nunca satisfacían sus gigantescas esperanzas. Al final desesperados, los Xel'Naga concentraron sus esfuerzos frustrados en el mundo más prometedor de todos los que habían construido. Aiur, un enorme mundo jungla en el extremo de la galaxia, en el que había nacido una raza de seres muy avanzados. Estos seres eran increíblemente adaptables a condiciones naturales y climáticas duras. Su fuerza y su velocidad no tenían igual entre las razas que los Xel'Naga conocían. La raza había desarrollado una sociedad tribal rudimentaria basada en la caza en grupo y reglas de guerreros. No obstante, su aspecto más característico era que se comunicaban unos con otros a través de un modo muy complejo de telepatía instintiva que les permitía trabajar en comunidad con gran eficacia. Los Xel'Naga estaban contentos con los avances de su última creación y reconocieron que la nueva raza era el primero de todos sus experimentos en evolucionar más allá de las restricciones salvajes de las formas de vida más básicas. Para distinguir su ascensión en el orden galáctico, los Xel'Naga dieron a la nueva raza el nombre de Protoss o "Los Primeros Nacidos".
       Los primeros Protoss vivieron en armonía, recluidos en el mundo de Aiur durante cientos de generaciones sin conocer nunca de la existencia de sus creadores XelNaga que les observaban desde lejos. Aunque los Protoss eran la especie más avanzada que surgió, los XelNaga todavía no estaban satisfechos con sus lentos avances y decidieron que era adecuado llevar la evolución de los Protoss más allá. Los Xel'Naga emplearon otro milenio más guiando sutilmente los pasos de sus hijos, hasta que al final tuvieron éxito llevando a los Protoss a un estado de sensibilidad y conciencia totales. Los Primeros Nacidos gradualmente se convirtieron en seres altamente intelectuales e introspectivos, consiguiendo niveles muy altos, no sólo en sus avances culturales, sino también en los avances personales e individuales. Exultantes con su éxito, los Xel Naga finalmente se dieron a conocer a los Protoss sin sospechar en el caos que estaba por llegar.`
      }
   ] 
  
    constructor() { }
  
    public getlistaInfo(){
      return this.listaInfo;
    }
}
